# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty

# Setup
title:               Greeting! I like Reb Lobster! lol
tagline:             "Eric Zhang"
description:         "Eric Zhang's Github"
url:                 https://Ericzhang90.github.io
baseurl:             ''
paginate:            5

# About/contact
author:
  name:              Mark Otto
  url:               https://twitter.com/mdo
  email:             markdotto@gmail.com

# Custom vars
version:             1.0.0
