# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty

# Setup
title:               Learn to Be Giant
tagline:             "Eric Zhang (iOS/Python developer)"
description:         "Eric Zhang's Github"
url:                 https://Ericzhang90.github.io
paginate:            5

# About/contact
author:
  gravatar:          https://avatars1.githubusercontent.com/u/11701625?v=3&amp;s=400
  name:              Eric Zhang
  url:               https://github.com/EricZhang90
  email:             lzhang.eric@gmail.com

# Custom vars
version:             1.3.0

future: true

permalink: /:year-:month-:day-:title/

hero:
  image: /public/we_will_be_giants_by_yalestewart.jpg
  caption: Original Artwork &copy; <a href="http://yalestewart.deviantart.com/art/We-Will-Be-Giants-370176475">Yale Stewart</a>
